name: Terraform Validation
on:
  pull_request:
    branches:
      - "*"

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "export GIT_TOKEN=${{ secrets.GIT_TOKEN }}" >> $GITHUB_ENV

      - name: Fetch code from private repo
        run: |
          cd environments/production
          git clone https://greqq:${GIT_TOKEN}@github.com/terraform-config.git
        working-directory: ./path/to/clone/repo
      #TODO: test this shit ... on commit
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: 1.0.0

      # - name: Terraform init
      #   run: terraform init

      # - name: Terraform validate
      #   run: terraform validate

      # - name: Terraform apply
      #   run: terraform apply -auto-approve
      # Upload a file to AWS s3

      # - name:  Copy index.html to s3
      #   run: |
      #     aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}/
